### ISSUE TITLE
question about loading many images

### ISSUE THREAD

**Issue by gc** [konvajs/use-image#1]
hey! im just looking for a bit of help, how would you recommend to load an arbitrary amount of images (could be 5, could be 100+), and considering they're image files and not URL's (i.e not using a URL to link to them, theyre files in my create-react-app project).

I was thinking it would be best to show a loading screen (dont even load in the stage/konva) until all of them are loaded

**Comment by gc** [comment]
nevermind, figured out a way myself :)

**Comment by kang5313** [comment]
> nevermind, figured out a way myself :)

 @gc Hi there, I'm facing the exactly same question with yours. Would you like to enlighten me on how you solve this problem?

**Comment by gc** [comment]
@kang5313 I think I saved all the images to a folder with an ID as the name, e.g. `123.png` where 123 is the ID, and then in my code i just used a URL referencing the ID.

**Comment by kang5313** [comment]
> @kang5313 I think I saved all the images to a folder with an ID as the name, e.g. `123.png` where 123 is the ID, and then in my code i just used a URL referencing the ID.

@gc Thanks for your quick response! May I know you are writing your own custom hooks to perform this or continue using this useImage hooks without any modifications on the codes?
