### ISSUE TITLE
Usage in loops

### ISSUE THREAD

**Issue by mhutfield-Itrinegy** [konvajs/use-image#12]
How would I use this in some kind of loop? I have an array of objects each with their own image and I want to make sure the image is loaded before drawing it to the konva canvas. I don't want a load of useImage statements, plus I don't know how many there will be to load. Any ideas? Thanks

**Comment by mhutfield-Itrinegy** [comment]
I bypassed this by creating images in a Promise.all and resolving on image load, then updating the state with the loaded image objects. However I'm still curious to know if the use-image hook can be used in this scenario.

**Comment by lavrton** [comment]
You should not use `useImage` inside a loop in one component. For such use case, you should:

1. load images manually and use just one setState. (looks like what you did)
2. Or From the array just render a set of components (like `<MyImage/>`) and then use `useImage` INSIDE `<MyImage/>`).

```js
const MyImage = ({url}) => {
   const [image] = useImage(url);
   return <Image image={image} />
};

const App = ({ arrayOfUrls }) => {
   return (
     <React.Fragment>
       {arrayOfUrls.map(url => <MyImage key={url} url={url}/>}
     </React.Fragment>
  );
}
```

**Comment by mhutfield-Itrinegy** [comment]
Thank you! Never thought of that.
