### ISSUE TITLE
Problems with img cache

### ISSUE THREAD

**Issue by istoros** [konvajs/use-image#13]
I need update coordinates of my image with setInterval, but everytime image is reloading (not caching)
How fix it?
My component:
`const Rocket = ({x, y}: any) => {
    const [ image ] = useImage(rocket_img);

    return (
        <Image
            image={image}
            width={44}
            height={82}
            offsetX={22}
            offsetY={62}
            rotation={45}
            x={x}
            y={y}
        />
    );
}`

**Comment by lavrton** [comment]
What do you mean by "reloading"? Can you make a demo?

**Comment by PawelGIX** [comment]
I have a demo.
https://codesandbox.io/s/blinking-use-image-x56vu

After loading, click on the stage, you will see flashing visible when you re-render the component. It looks as if the image has not been available for a while, even though the browser has it in the cache.

**Comment by lavrton** [comment]
Even if it was previously loaded, it is still "loading" in an async way on the component mount. If you don't want to see flashes - download it upfront.
