### ISSUE TITLE
undefined image object

### ISSUE THREAD

**Issue by SMSmith** [konvajs/use-image#14]
When I run this locally, everything works fine.  When I run it server side, the status changes to "loaded" but the image returns undefined.  Any idea what might be going on?  It's clear from the network monitor that the images are loading somewhere.  They're just not ending up in the final render.  

use-image@1.0.5
konva@6.0.0
react@16.13.1
react-dom@16.13.1

**Comment by lavrton** [comment]
Can you check development VS production builds?

**Comment by SMSmith** [comment]
@lavrton What do you mean by that?  My local development build works and the libraries match to my production build (server side).

**Comment by lavrton** [comment]
The production build may minify the code. Minified code may work differently.

It will be better if you can make a demo.

**Comment by SMSmith** [comment]
The production code is minifying the code -- how do you think that's breaking it? 

[Here's a production example](https://data.bedrockwireless.com/test).  

The Konva logo should show up on the canvas.  It works unminified on my machine.

**Comment by lavrton** [comment]
That is a bad minified. It produces the wrong code. What tools do you use to make a build?

**Comment by lavrton** [comment]
I just published `1.0.6` that may fix the issue. But I still need to know what do you use for a production build. I am sure they have a bug in minified.

**Comment by SMSmith** [comment]
npm run build (react) <-- minifies
serve@11.3.2 <-- runs the web server

**Comment by lavrton** [comment]
What do you use in `npm run build`?

**Comment by SMSmith** [comment]
npm is doing the minification.
npm@6.13.4

**Comment by SMSmith** [comment]
Actually, it's probably react-scripts@0.9.5

**Comment by lavrton** [comment]
Looks like it is just too old and has such a bug.
