### ISSUE TITLE
Could not resolve dependency: peer react@"^16.8.0" from use-image@1.0.6

### ISSUE THREAD

**Issue by deadcoder0904** [konvajs/use-image#18]
I can't install `use-image` on a project using `react@17.0.1` due to:

https://github.com/konvajs/use-image/blob/7fcad1d8ffcb581a0e9681f5c9e44162c2fcb6c2/package.json#L27

Not sure why the `peerDependency` uses a versioned number. It can be `@latest`, no?

Can you please publish a newer version using `17.0.1` or preferably `latest`?

**Comment by lavrton** [comment]
Fixed.

**Comment by deadcoder0904** [comment]
Damn that was super fast. I have another issue now, not sure if it's related:

```bash
➜ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frameit@1.0.0
npm ERR! Found: konva@7.2.2
npm ERR! node_modules/konva
npm ERR!   konva@"^7.2.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer konva@"^3.2.3" from react-konva@16.8.6
npm ERR! node_modules/react-konva
npm ERR!   react-konva@"^16.8.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/deadcoder0904/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deadcoder0904/.npm/_logs/2020-12-19T13_05_38_158Z-debug.log
```

How can I solve this one?

**Comment by lavrton** [comment]
Looks like you are using an old version of `react-konva`.

**Comment by deadcoder0904** [comment]
Oops that was true. As `use-image` wasn't working, I tried downgrading versions manually & they were out of sync. Removed `konva` & `react-konva` from `package.json` & installed them separately again to download latest version. That worked fine.

Thanks for `konva`, it makes Canvas in React really simple.
