### ISSUE TITLE
Image not loaded

### ISSUE THREAD

**Issue by AidanRRR** [konvajs/use-image#20]
Anyone else some issues where the image is not been loaded correctly?

Struggling with this, as it does not always seem to happen. Am I missing something? Thanks!

````
import { Image, Rect } from 'react-konva';
import useImage from 'use-image';

import moon from '../../../assets/grid/moon.svg';

export function MoonItem({ width, height, rotation }) {
  const [image] = useImage(plant);
  return (
    <>
      <Image
        image={image}
        x={width / 2}
        y={height / 2}
      />
    </>
  );
}
````

**Comment by lavrton** [comment]
Anyways to reproduce it? what do you have inside the `moon` variable? Static path to the image? did you check it?

**Comment by AidanRRR** [comment]
https://github.com/konvajs/konva/issues/677#issuecomment-504596837 Has to do with this. My bad!
