### ISSUE TITLE
pass upload image to useImage

### ISSUE THREAD

**Issue by Mrezagolbaba** [konvajs/use-image#21]
I have some input for upload the image and then show this image in Layer with useImage.
how to pass an image to useImage when uploading an image.

**Comment by lavrton** [comment]
If you don't want to upload an image to the backend (to get URL), you can just convert the local image into a base64 data URL. Then you use as `src` for `useImage`

**Comment by Mrezagolbaba** [comment]
and can I use PFD base64 in this hook? @lavrton

**Comment by lavrton** [comment]
No. PDF is not an image.You may need something like this: https://mozilla.github.io/pdf.js/
