### ISSUE TITLE
Android system gives a wrong image size.

### ISSUE THREAD

**Issue by rusicsemenov** [konvajs/use-image#30]
Hello, I have a file with a big resolution, more than 11000px width, and 10000px height (11297 X 10550). After the file upload image size on the Android system has (7061x6594)
![3gfVJ](https://user-images.githubusercontent.com/20163858/213947504-f72ea1df-062e-4e72-ad03-0994c76a6cd7.png)
IOS and the Web have a normal size.  [Here is an example](https://codesandbox.io/s/damp-frog-x5mgnm?file=/src/NativeImageLoader.tsx:836-848)

**Comment by lavrton** [comment]
I don't think I can do anything here from `use-image` package side. It looks like an android browser bug or limitation of max image size.
