### ISSUE TITLE
How to use "use-image" with local image or image stored in variable ?

### ISSUE THREAD

**Issue by MGMehdi** [konvajs/use-image#33]
Hi,
How can I display an image that is stored in local or in variable ? 
I don't understand this response : https://github.com/konvajs/use-image/issues/21

It's to display the image in KonvaJS

**Comment by MGMehdi** [comment]
Hi, 
if the user upload an image and I want to display it inside the canvas or if I have an image in the `public` folder, how can I achieve this without uploading the image on the server

**Comment by lavrton** [comment]
I am sorry. I am not sure how to help you. The question is not really related to `use-image` package.

When user uploads an image, you can convert it into base64 data url, and then you can use it for `use-image` hook.
