### ISSUE TITLE
Performance Sucks (flickers)

### ISSUE THREAD

**Issue by rosendolu** [konvajs/use-image#34]
## Trouble

When use `useImage` render multiple images, It sucks as bellow last pic.

```js
  const [image] = useImage(url);
 return <Image width={w} height={h} ref={imgRef} image={image}></Image>
```

https://github.com/konvajs/use-image/assets/42633099/72a2213f-1792-45d6-9d49-74c241c4456a

## Resolution

```js
 const [imageFrame, setImage] = useState(new globalThis.Image());
// imageFrame.src = 'xxx'
// layer.draw();
 return <Image width={w} height={h} ref={imgRef} image={image}></Image>
```
So ,i wonder why we need a new instance? just In order to avoid manual `draw layer`?

```js
  React.useLayoutEffect(
    function () {
      if (!url) return;
      var img = document.createElement('img');
    [url, crossOrigin, referrerpolicy]
  );
```

**Comment by lavrton** [comment]
Are you sure it is a performance issue? The image may flick just because it is not loaded yet, so `useImage` returns `undefined`, so it is not rendered.

**Comment by rosendolu** [comment]
I guess yes，in `React way`, last frame is better then the prelude of next frame, `undefined`  is more accurate but not  UE  friendly

**Comment by lavrton** [comment]
I want to keep the current behavior of `useImage`. For your use case, there are two options:

1. Add extra hook/memo/ref to track last available image. And use it when new is not loaded.

```js
const [image] = useImage(url);
const lastImage = React.useRef();
lastImage.current = image || lastImage.current;
const imageToPassIntoComponent = lastImage.current;
```

2. Or just copy/paste `useImage` source into your code and modify it according to your needs. You can also drop some amount of code that is not relevant to your use case.

**Comment by rosendolu** [comment]
Thx for the solution. Could you please explain why we need a new `img`

**Comment by lavrton** [comment]
Mostly just this "just In order to avoid manual draw layer".

**Comment by mksh** [comment]
I had the same flickering issue with react-konva and use-image and was able to resolve it with useMemo like this:

```tsx
const imageDataUrl = useState(...)|useSomeContext(...)

const nativeImage = useMemo(() => {
  if (!imageDataUrl) {
    return null
  }
  const img = new Image()
  img.src = imageDataUrl
  return img
}, [imageDataUrl])
const imageRef = useRef(null)

...

<KonvaImage image={nativeImage} ref={imageRef} />
```

This way konva image shape keeps the latest image data until the new one available, and no react rerender is happening until new one is there.

In my case I generate image in data url form fully in browser, but it can be made into react state with tool like tanstack-query in case if generated on server-side.
