### ISSUE TITLE
Cannot set property '_id' of undefined

### ISSUE THREAD

**Issue by slillo** [konvajs/use-image#4]
Here is  an [example](https://stackblitz.com/edit/js-gswrwv?embed=1&file=index.js) that just ouput: Cannot set property '_id' of undefined

**Comment by lavrton** [comment]
`<Image>` is a react component. You need to use it from `react-konva`. Not from `konva` package.

```javascript
import React, { useState } from "react";
import { render } from "react-dom";
import { Stage, Layer, Rect, Circle, Image } from "react-konva";
import useImage from "use-image";
```
