### ISSUE TITLE
Feature request: Re-fetching every x seconds

### ISSUE THREAD

**Issue by ohlr** [konvajs/use-image#9]
I am trying to modify the code to make it re-fetch the underlying image every x seconds.
[Something along these lines](https://dev.to/chriswcs/custom-react-hooks-creating-a-useclock-hook-23pd).

However, I can't get it to work :/

Edit:
Wrapping the fetch, similar like here: [stackoverflow](https://stackoverflow.com/a/59146853/9177173) works, but it does not cause a rerender.

**Comment by lavrton** [comment]
Why you may need to refetch the image?

**Comment by ohlr** [comment]
Because the underlying image is changing

**Comment by lavrton** [comment]
I think the best way is to change URL of the image. Like with `get` parameter, so the image is not cached.
Using the code from linked post:
```javascript
const clock = useClock();
const url = imageUrl + '?token=' + clock;
const [image] = useImage(url);
```

**Comment by ohlr** [comment]
The problem with this approach is that the status transitions constantly between loading and loaded.

**Comment by lavrton** [comment]
Just write your own custom hook, that will use the old image while new one is loading.
